---

- name: Reload initd
  command: initctl reload-configuration

- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart kafka service
  service:
    name: kafka
    state: restarted
